cmake_minimum_required(VERSION 3.16)
project(JizaTorrent LANGUAGES C CXX OBJCXX)
set(CMAKE_CXX_STANDARD 17)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(encryption OFF CACHE BOOL "" FORCE)
set(deprecated-functions OFF CACHE BOOL "" FORCE)
set(build_tests OFF CACHE BOOL "" FORCE)
set(build_examples OFF CACHE BOOL "" FORCE)
add_subdirectory(${TORRENT_SOURCE} libtorrent)
add_library(JizaTorrent STATIC JizaTorrent.mm)
target_link_libraries(JizaTorrent PRIVATE torrent-rasterbar "-framework Foundation")
target_compile_options(JizaTorrent PRIVATE -fobjc-arc)
